### PR TITLE
Implement Robust orientation

### PR DESCRIPTION
**Pull request by dgleich**
This directly includes the AdaptivePredicates.jl code for robust orientation. 

Also, this gives a speed improvement!

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
How much of a speedup did it actually give?

**Comment by dgleich** [comment]
Interesting, this shows a different between the Intel proc and Apple procs!

@btime triangulate(pts2) setup=begin pts2=rand(StableRNG(1), Point2f, 1_000_000); end

On my Intel iMac Pro (Julia 1.10.2):

842 ms for using the code from AdaptivePredicates.jl 
859 ms for using the code on master (orient ifsure) 

On my M2 MacBook Air (Julia 1.10.1):

469ms using the code from AdaptivePredicates.jl 
453ms using the code on master (orient ifsure)

**Comment by dgleich** [comment]
Hey @DanielVandH, I edited and incorporated your ported incircle test here too from Adaptive Predicates. Any objection to including it directly here? I like to try and avoid dependencies if possible. I added you to the list of people as authors of the robust.jl file.

Adding the robust incircle test does give a small overall slowdown. (more like 900ms on Intel now now; more like ~500ms now on Mac).

**Comment by DanielVandH** [comment]
I've no problem with you including it directly, that's fine. I've done similar copies in DelaunayTriangulation.jl for avoiding other dependencies.

I like what you did with trying to avoid caching for as long as possible. I wanted to do that initially but.. lazy. The slowdown isn't too surprising but it's a nice middle ground between exact and inexact I'd say. Is your benchmark actually over a million points as you write above? I tried that and get a much longer time.

**Comment by dgleich** [comment]
Thanks. I added the performance test to this pull request to see what the CI machines give.

**Comment by DanielVandH** [comment]
Oh I see. I just ran it again and get a decent result (~1.2s). Last time I got like 45 s.. don't know what happened there. Must've got unlucky. That's an impressive speed! Is it using spatial sorting?

**Pull request merged**
